services:
  - type: web
    name: car-rental-app
    env: java
    region: frankfurt
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    healthCheckPath: /
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production

databases:
  - name: carrental-db
    databaseName: carrental
    user: carrental_user
    plan: free